# This file was generated by GoReleaser. DO NOT EDIT.
cask "wbsp-app" do
  version "0.1.6"

  on_macos do
    on_intel do
      sha256 "0e1c25823414e64b299bd6bae1a4bacf2a9dccb40f2963962cb93b84a0f9e1e4"
      url "https://get.wbsp.ai/#{version}/wbsp-app_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "505918a240ff3acb5c4182a6b514e1fa74f3a2d7c009d7bda94f9490d9381543"
      url "https://get.wbsp.ai/#{version}/wbsp-app_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "0553c1ede286eb13a723259f8f3d4fb707fc49dce252f3845e21643f4415391c"
      url "https://get.wbsp.ai/#{version}/wbsp-app_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "7458e1f77c4f40bed470204f919ae169b669d7e466ae0092c7ee1d5fbf6f24fc"
      url "https://get.wbsp.ai/#{version}/wbsp-app_#{version}_linux_arm64.tar.gz"
    end
  end

  name "wbsp-app"
  desc "Deploy and manage applications on the WBSP platform"
  homepage "https://github.com/worlds-biggest-software-project/wbsp-platform"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "wbsp-app"

  # No zap stanza required

end
