# This file was generated by GoReleaser. DO NOT EDIT.
cask "wbsp" do
  version "0.2.58"

  on_macos do
    on_arm do
      sha256 "8b4b5955a579c5ef6ac8963bbe8e0aed66eaed69c54a0b78d583436ecd91bab0"
      url "https://get.wbsp.ai/#{version}/wbsp_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "02a0d116f579f4afcbb42d19edc9816e84d1beb51bcd46e9e5ce4836ebf65167"
      url "https://get.wbsp.ai/#{version}/wbsp_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "d015b79124b42eab96729748814c4216fcb9d1e23df116e4715d7630253a08cd"
      url "https://get.wbsp.ai/#{version}/wbsp_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "45cdad4e3008e32756be90fda5bbfee8eae450a235f478346ac6128dfa5b422a"
      url "https://get.wbsp.ai/#{version}/wbsp_#{version}_linux_amd64.tar.gz"
    end
  end

  name "wbsp"
  desc "Deploy and manage applications on the WBSP platform"
  homepage "https://github.com/worlds-biggest-software-project/wbsp-platform"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "wbsp"

  # No zap stanza required
end
