# This file was generated by GoReleaser. DO NOT EDIT.
cask "wbsp" do
  version "0.2.67"

  on_macos do
    on_arm do
      sha256 "06fd3bba8a5e6bfaf6a52953002d5f9e486702d43f6368d76781cd590a3b7f08"
      url "https://get.wbsp.ai/#{version}/wbsp_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "4f2198af760ad594d0ec3b921767111079aced29f25862a640d33f1b60bc561b"
      url "https://get.wbsp.ai/#{version}/wbsp_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "b47d3829acac5b1a578b1f983eadef09d7936e160b676402886b2a1040c32a57"
      url "https://get.wbsp.ai/#{version}/wbsp_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "553321268e13684a7153f2f92e637ee4ead9827067f473ddc1007a6f18fb4e89"
      url "https://get.wbsp.ai/#{version}/wbsp_#{version}_linux_amd64.tar.gz"
    end
  end

  name "wbsp"
  desc "Deploy and manage applications on the WBSP platform"
  homepage "https://github.com/worlds-biggest-software-project/wbsp-platform"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "wbsp"

  # No zap stanza required
end
