# This file was generated by GoReleaser. DO NOT EDIT.
cask "wbsp" do
  version "0.2.32"

  on_macos do
    on_intel do
      sha256 "3c4879bae20e05897810bc1be368fb18a5e9908bdc9814ab80182356f43f7367"
      url "https://get.wbsp.ai/#{version}/wbsp_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "ccc0a71f9b1af1e0dd05ea23e73819781f612bd54076620b705457ae8a851d2d"
      url "https://get.wbsp.ai/#{version}/wbsp_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "70270175a39182df52ff5440e7f831340af69d98a6d4ae22a70f11d9c5446064"
      url "https://get.wbsp.ai/#{version}/wbsp_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "bd81ce117f8c57969c17d3f7b0e96e33708f061be11f90bf3e99b3339cd70622"
      url "https://get.wbsp.ai/#{version}/wbsp_#{version}_linux_arm64.tar.gz"
    end
  end

  name "wbsp"
  desc "Deploy and manage applications on the WBSP platform"
  homepage "https://github.com/worlds-biggest-software-project/wbsp-platform"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "wbsp"

  # No zap stanza required

end
