# This file was generated by GoReleaser. DO NOT EDIT.
cask "wbsp-app" do
  version "0.1.5"

  on_macos do
    on_intel do
      sha256 "b44501c12f2c66d53bf58183b9627da1d36b8b0b937c7f41ea4ba1d612f39a26"
      url "https://get.wbsp.ai/#{version}/wbsp-app_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "5e489384fbdf88c51330e6b4c1a16d7de96356903537a24a4e28ed85379439c3"
      url "https://get.wbsp.ai/#{version}/wbsp-app_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "42d2acaa8a2532763b8ee9e5f8ddc7920fad7ac2a12a9303a7c7c691bae96404"
      url "https://get.wbsp.ai/#{version}/wbsp-app_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "16689629ca98427616affa7c251f284155f78f909664604eeb08187381249f0d"
      url "https://get.wbsp.ai/#{version}/wbsp-app_#{version}_linux_arm64.tar.gz"
    end
  end

  name "wbsp-app"
  desc "Deploy and manage applications on the WBSP platform"
  homepage "https://github.com/worlds-biggest-software-project/wbsp-platform"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "wbsp-app"

  # No zap stanza required

end
